### PR TITLE
Make cqrs::TypedEvent static

### PR DESCRIPTION
**Pull request by 50U10FCA7**
For optimization purposes result of cqrs::TypedEvent::event_types() should be generates once.

There's two ways to do implement this:

Add additional trait cqrs::TypedEventStatic which provides static version of event_types;
Replace implementation of cqrs::TypedEvent to make it static.

### CODE REVIEW

**Comment by 50U10FCA7** [comment]
@tyranron Reimpl way has problem with generic params. `once_cell::sync::Lazy` can't pass generics from outer function. I think we can use something like [this](https://crates.io/crates/generic_static) to solve this problem.

**Comment by tyranron** [comment]
@50U10FCA7 please, remind me, why we don't use arrays and slices and `const`?

**Comment by 50U10FCA7** [comment]
@tyranron Most traits implemented on `Vec<T>` but not for `&[T]`. In our case its `postgres_types::ToSql`. 

Also checked the variant with constant slices and it doesn't work with generics too. At now it's impossible to pass generic to constant. Compiler throws error `can't use generic parameters from outer function`.

**Comment by 50U10FCA7** [comment]
@ilslv ping

**Comment by ilslv** [comment]
@50U10FCA7 I believe you can hack around it by generating separate non-generic struct and implement `Event` on it: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=642ff543d4bb7834bc669f3ec862e804)

**Comment by 50U10FCA7** [comment]
@ilslv There still problem with const evaluation: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a85a3cbe1aa530bbca69e2f140e79721). Const block is required because of nested event types concatenation. Concatenation uses [this solution](https://www.reddit.com/r/rust/comments/lghv60/comment/h6l3386/?utm_source=share&utm_medium=web2x&context=3).

**Comment by ilslv** [comment]
@50U10FCA7 please provide more exact MRE, because I don't understand why are you using inline const in `Len` implementation and why using `<Self as Len>::LEN` isn't possible.

**Comment by 50U10FCA7** [comment]
@ilslv 

Full MRE looks like this. I tried to avoid the problem with:
- [Nested assoc type](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=56c3e0408cd935e32d41f90d4f3a02ae)
- [Self's assoc type]https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b2ed5a1ad3b574e5797c81711aff3eb2)

**Comment by ilslv** [comment]
@50U10FCA7 I've got [pretty close to make it work][1], but compiler warned [about this issue][2]

> As we only allowed generic constants where the actual type did not matter, it should always be possible to replace the generic parameters with dummy types. For example `[0; std::mem::size_of::<*mut T>()]` can be changed to `[0; std::mem::size_of::<*mut ()>()]`.

So I think we can simply replace every generic parameter with `()`, because thats what compiler will eventually try to do. 



[1]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e215a215634acdef9b4ef7610fcf9a3d
[2]: https://github.com/rust-lang/rust/issues/76200

**Review by tyranron — APPROVED** [review]

**Pull request merged**
